### ISSUE TITLE
[Enhancement] Remove the modal box when copying passwords from the GUI

### ISSUE THREAD

**Issue by dwbfox** [JFreegman/SpicyPass#2]
Keeping up with the minimalist ethos, it seems counterproductive to display a confirmation box whenever a password is copied to clipboard using the GUI. A small toaster message or even no message at all would better fit the minimalist idea of this tool.

**Comment by JFreegman** [comment]
Agreed and done https://github.com/JFreegman/SpicyPass/commit/6260daa9c0d6774adb3062928fa2939b9fb99452
